### ISSUE TITLE
Unexpected HTTP response status 401

### ISSUE THREAD

**Issue by tweeks024** [graylog-labs/graylog-plugin-hipchat#13]
Hello, I'm getting a 401 error when trying to use this plugin.  I've tried using the same API token as I'm using with a working jenkins server and also an admin api token but both fail.  I've also tried the room by ID and by name but get the same results.  Can you please let me know what could be causing this?

```
Alarm callback <HipChat alarm callback> failed. Skipping.
org.graylog2.plugin.alarms.callbacks.AlarmCallbackException: Unexpected HTTP response status 401
```

**Comment by tweeks024** [comment]
@joschi sorry forgot i opened this one, was using apiv1 instead of apiv2 in hipchat, all set now

**Comment by joschi** [comment]
@tweeks024 Thanks for your feedback!
